jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Build Project
        run: npm run build
        env:
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4